// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Ping
---
*/
package cmds

import (
	"context"
	"errors"
)

func HealthPingPost(ctx context.Context, args []string) (*string, error) {

	return nil, errors.New("Not implemented")
	// result, pwsherr := execution.ExecutePowerShell("john", "*", "magicbox-site", "00-health", "10-ping.ps1", "", "-pong", args[0])
	// if pwsherr != nil {
	// 	return nil, pwsherr
	// }
	// utils.PrintSkip2FirstAnd2LastLines(string(result))
	// return nil, nil

}
