// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Analyse Page
---
*/
package cmds

import (
	"context"
	"os"
	"path"

	"github.com/365admin/magicbox-site/execution"
	"github.com/365admin/magicbox-site/utils"
)

func ProcessAnalysePagePost(ctx context.Context, body []byte, args []string) (*string, error) {
	inputErr := os.WriteFile(path.Join(utils.WorkDir("magicbox-site"), "page.json"), body, 0644)
	if inputErr != nil {
		return nil, inputErr
	}

	result, pwsherr := execution.ExecutePowerShell("john", "*", "magicbox-site", "30-process", "30-analyse-page.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
