// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Download medias
---
*/
package cmds

import (
	"context"
	"os"
	"path"

	"github.com/365admin/magicbox-site/execution"
	"github.com/365admin/magicbox-site/utils"
)

func SyncDownloadMediasPost(ctx context.Context, body []byte, args []string) (*string, error) {
	inputErr := os.WriteFile(path.Join(utils.WorkDir("magicbox-site"), "analysed-pages.json"), body, 0644)
	if inputErr != nil {
		return nil, inputErr
	}

	result, pwsherr := execution.ExecutePowerShell("john", "*", "magicbox-site", "30-sync", "40-download-images.ps1", "", "-siteUrl", args[1])
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
