// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Get Site Pages
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/magicbox-site/execution"
	"github.com/365admin/magicbox-site/schemas"
	"github.com/365admin/magicbox-site/utils"
)

func DownloadSitePagesPost() usecase.Interactor {
	type Request struct {
		Siteurl string `query:"siteUrl" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.Pages) error {

		_, err := execution.ExecutePowerShell("john", "*", "magicbox-site", "20-download", "20-getsitepages.ps1", "", "-siteUrl", input.Siteurl)
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("magicbox-site"), "pages.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.Pages{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Get Site Pages")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Download")
	return u
}
