// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Update Web
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/365admin/magicbox-site/execution"
)

func ProcessUpdateWebPost() usecase.Interactor {
	type Request struct {
		Sitename string `query:"siteName" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magicbox-site", "30-process", "50-updateweb.ps1", "", "-siteName", input.Sitename)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Update Web")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Process")
	return u
}
