// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Download medias
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/365admin/magicbox-site/execution"
	"github.com/365admin/magicbox-site/schemas"
	"github.com/365admin/magicbox-site/utils"
	"github.com/swaggest/usecase"
)

func SyncDownloadMediasPost() usecase.Interactor {
	type Request struct {
		Siteurl string                `query:"siteUrl" binding:"required"`
		Body    schemas.AnalysedPages `json:"body" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {
		body, inputErr := json.Marshal(input.Body)
		if inputErr != nil {
			return inputErr
		}

		inputErr = os.WriteFile(path.Join(utils.WorkDir("magicbox-site"), "analysed-pages.json"), body, 0644)
		if inputErr != nil {
			return inputErr
		}

		_, err := execution.ExecutePowerShell("john", "*", "magicbox-site", "30-sync", "40-download-images.ps1", "", "-siteUrl", input.Siteurl)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Download medias")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Syncronise SharePoint with web")
	return u
}
